name: "Build"
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: ebubear
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: '(-source$|\.tf$|docker)'
    - run: nix build .#bear --no-link

    - run: nix build .#bear_docker -o bear_docker.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: bear_docker.tar.gz
        path: bear_docker.tar.gz
    - run: rm bear_docker.tar.gz
